[package]
name = "sdf_mesh"
version = "0.1.0"
edition = "2024"
default-run = "sdf_mesh"

[dependencies]
bevy = "0.19.1"
image = { version = "0.25", default-features = false, features = ["png"] }

[features]
default = ["dev"]
dev = ["bevy/file_watcher"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
